#!/bin/bash

set -eux

codename=$1
distribution=$2
changes_file=$3
config_path=$4
repo_dir=$5

sudo reprepro -C $distribution -V -b $repo_dir include $codename $changes_file
RET=$?

# Cleaning files
if [ $RET -eq 0 ]; then
    dir=$(cd `dirname $changes_file` && pwd)
    for f in $(get_files ${changes_file}); do
        ! [[ $f =~ \.orig\.tar\.(gz|xz)$ ]] && sudo rm -f ${dir}/$f
    done
    sudo rm -f $changes_file
fi

exit $RET
